src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Balance_Amount__c</fullName>
        <label>Balance Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Donation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field specifies that these installment type records are related to which donation record.</inlineHelpText>
        <label>Donation</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Installments</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Installment_Amount__c</fullName>
        <label>Installment Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <inlineHelpText>This picklist is for the payment status.</inlineHelpText>
        <label>Payment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CompleteAllInstallmentsClass.cls
global with sharing class CompleteAllInstallmentsClass{
    webservice static String completeOpenInstallments(Id donationID,String donationOwnerEmail){
        Integer countInstallment=0;
        Decimal totalAmountClosed=0.0;
        List<Opportunity> relatedInstallmentRecords=[SELECT Id
                                                          , Payment_Status__c
                                                          , Balance_Amount__c
                                                          , Installment_Amount__c
                                                       FROM Opportunity
                                                      WHERE Donation__c=:donationID
                                                        AND Payment_Status__c='Open'];
        for(Opportunity objInstallment: relatedInstallmentRecords){
            totalAmountClosed+=objInstallment.Installment_Amount__c;
            objInstallment.Balance_Amount__c=0;
            objInstallment.Payment_Status__c='Completed';
            countInstallment++;
        }
        //Updating the installment records.
        try{
            update relatedInstallmentRecords;
        }
        catch(Exception e){
            return e.getMessage();
        }
        
        Messaging.SingleEmailMessage donationMail = new Messaging.SingleEmailMessage();
        String[] recipient=new String[]{donationOwnerEmail};
        donationMail.setToAddresses(recipient); 
        donationMail.setSubject('Open Installments Completed.');
        donationMail.setPlainTextBody(countInstallment+' Installments completed'+'\n Amount Donated= '+totalAmountClosed);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {donationMail});
        String successMessage='Open Installments completed.';
        return successMessage;
    }
}